//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialClub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialClubDBEntities : DbContext
    {
        public SocialClubDBEntities()
            : base("name=SocialClubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAfiliado> tbAfiliados { get; set; }
        public virtual DbSet<tbMembresia> tbMembresias { get; set; }
        public virtual DbSet<tbSexo> tbSexoes { get; set; }
        public virtual DbSet<tbLogin> tbLogins { get; set; }
        public virtual DbSet<tbSocioInfo> tbSocioInfoes { get; set; }
    }
}
